# Generated by Django 2.0.8 on 2018-09-20 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jogo', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('desenvolvedora', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Produtora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeProdutora', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='jogos',
            name='produtora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Produtora'),
        ),
    ]
